# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('follow_ids', models.TextField()),
            ],
            options={
                'db_table': 'man_man',
            },
        ),
    ]
