# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 11:09
from __future__ import unicode_literals

from django.db import migrations

def set_relationship(apps, shema_editor):
    Person = apps.get_model("people", "Person")
    for person in Person.objects.all():
        following = person.follow_ids.split()
        following = map(lambda i: Person.objects.get(id=int(i)), following)
        person.following.add(*following)

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_following'),
    ]

    operations = [
        migrations.RunPython(set_relationship)
    ]
