# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20170312_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='people.Person'),
        ),
    ]
