# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20170312_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='follow_ids',
        ),
    ]
